### ISSUE TITLE
FR: Display Jack CPU load and xrun count

### ISSUE THREAD

**Issue by x37v** [Cycling74/rnbo-runner-panel#116]
the latest beta has them in `/rnbo/jack/info`.. likely a nice little status thing that is persistent across views

**Comment by fde31** [comment]
Hm which version specifically? I'm kinda not able to find it in the jack state info running `1.3.2-xnor-runner-1-3-2.0`

**Comment by x37v** [comment]
install the latest alpha `1.3.2-alpha.1` and you should see it
