### ISSUE TITLE
UI doesn't render inport/outports correctly with names that have "/" in them correctly

### ISSUE THREAD

**Issue by x37v** [Cycling74/rnbo-runner-panel#130]
There should be 2 outports in the UI, and "monome" isn't their full path.

patcher

<img width="464" alt="image" src="https://github.com/Cycling74/rnbo-runner-panel/assets/65796/a34ea727-c5d9-416f-9fea-512d88edfe8a">

UI

<img width="882" alt="image" src="https://github.com/Cycling74/rnbo-runner-panel/assets/65796/ee514efb-3a12-4f79-83b1-b77fa2eaeb92">

see the attached patcher

<pre><code>
----------begin_max5_patcher----------
2422.3oc6aszaiiiD9r8uBAcrQhCenWdNMX28R.1A8.rX2KAKDjkns4zxTdk
nRROM5429PR8vj5gibhs2LAMZzINrHKVr9HqpXQWea9L6UYOSJrs9IqGrlM6
aymMS0jrgY0+8L6cQOGmFUn5lMi7T1pey9lJROFkyh1QTTxYqx9iFBbxy79s
xJ2kUxSIbEuf0stOhGukx1DlSh4UxxxkNK.2XA8T+xAH+IBs.X8eqGSEa3ec
OoZ.1ozBwXaHSSTStPRuEpM4TV24VJdORxKnYL0HfKvKP2FkteazBfst.Rxq
0J0pkY1qooDswVyxY1Q62q07LsgH0k+VlhQA2z1DkU0jWaS4jGoMiG01ZTtP
MwE5nx7JM9ydN1GXSVBImURUhRUieediHovOIRUrOJ9.b0LZ6CZdrSktFqz+
vkKk+NvCbP2K1grIMK9KDkNFzzX1dBix1mSJHLdDuV5aImPVGUlxCWmw3Eze
WICPAhND800x3fDa2u8Oi3GV.axoIYLoLX.ExlalsGrftpEkq9ZQ0CVz9AFr
X2iPsLBwBwZrrXUTtDoVkRzgJadVVpIo1wkRVyqIumxXcTh7r8iSLmtY6QF6
pLAwcGi2JJEgkrJpghME7vhnGMU17nzz5S4lr+4HFcWDmvoUH.BzRjvhDKzs
Ew4YooFq2JJON.kDwl7XxSzD9V0DouWPzc59l8P1snbBcCofa1FOZSgYKE7u
Voz0ZpbU8g3PNY29TwpvrChiGBCHEaydpntiM6yNnWn7Z1VxTeNwVS2bvJp9
4ccqoFseLqplFPEV51mkystamXW3NxcxMr2Il76jFeRuS.V5CyzBKPix.VYQ
tH0gcWe04hkdp+Bqc7nisTuNSUO6os1TCEhedTXDmmSWUxqzNy5oEDpABOpB
JZar0rUKyJYz+WIoQPpTHg8DHUWKH4znzAEoVif5rocZ+974sS+4GESyhRDV
eKr.iiVvogVHk2PO+AAqd9EsGCKcmLVRYqyFC9XDRRw8Lg0PVL495Npw.oWq
MJGO5bPmEBghsujaP1ftfEhcQeN+Wyy12k6l1D9aQrMV7LKwdtMaH4VREdzF
xBayQPKhRoQcOfnlHY6Mmj0UbJaHB8ZTs47tiSPId6HDoBKJ4Q6FfRBQ3tLV
XKJYngIwiAVuMXq8Jwp0Vij9wF0AK0h+bnW+kJVY8zVByp17nEsvRtoljzU8
V6rVf6Cv0yftGd408UmhNlxWEt4fq6+STZIoiEsdfi37RNubuBBOC.jN6NK5
6KgR8HabmOrdpxxfgi095nVC5UlQN1b9VMbrMan8DIGhE1XQYnSUtal9Zo4v
6Ir66hbbcZqssjz8shdimNaCm.xMaed83cvz27fcQDBdtHj+7tasrqur08J4
7VrGDD3AcCLX+VABSJ90Jkw8e1bE8BAbzHMg8badZQbztptNgb7IwMcd0AaD
TERXfJjCL7MFqgynwZfdswMVeVbxf3mB6IHmF58oqDrItf9Wrnx+8pAOmp.E
gp34ceqfGdTvCekCTL67DlXVO2Dui7RNwPOFOzBJCdNTRBfdkvsgvo3JhkbJ
sHojcDF2B9wKduWLV6JswKEvG3nvB5xBKniBKne.Ki.K3KKrfOJrf+ArLHrj
RXapRK3zPFznHy1rmr1Ew9pEW5jrPBQROr1+UTw2UAeD8GsfeNzd7s0amEpM
JixEgJQ+chkr4u8yU4GW5y96VUe15Ip.09Kspsu20yzkSg1mzokytm3S6xq2
LkkD57ujNIuXuIgGe9E9SxV+kHsAYim.jimxf9C7Uby+t1UMt0eOhl2tpG4o
caeDDhgtHWO3a419S8NmMVUsMjzC9p.Kl70Qkq2vd2t5ztQpRmcctT5K7HTB
i0u5GgBq+FTH.3kdCJz6s2fBcDDD8d5MnJYSI2B3ojaAHT88Bn5qmwDxsvM0
+eLP0+i2iQoXj0.lceGkrgWLR9WHWCBf9rjrg+uleAv6gj571uxjXNPmcr3Z
mTgONXA9riEW6LI7AAKtnoRnxk5ORlvaMYB0glLdVD9.jj4KeJFF+8uen4Ev
67Ek8Tha45852pvJdk2N+0GJwaHaBJeumCA9Zk9CkCpyg.eAR4gQNE5af0Hq
BCP17FVCzgokYAnOBiw.LBcUxrvqIGBUqsvd2e5zxhPsF55bETgwkdoQ3Kju
9Feo6fphEvA+Feoa3n2BEb8RsPkJJrm7bZnZEWFBUO7UeOkxF6asrRUKoOLb
WjUlG2nNq2+YgLTqIByETVac.7P6WDDKA5LoMauFY.LAY.egkA3DkA3ERFbm
ndv6BpGbNAr.cgjA7DkAzETO.mnL3OpLb33ZSQvrZSbVZk6qGjtKvPrOx0YI
.tzCDH3yBX6e5G3fgxlPPnumiOvMH.gcwhce5EAiACWhV5.Q2X7Irq7icFUc
L.FCF6565.7QdddPu.0XcgttdtKWBc.POeUSAdP+.O+.juCz0wuCeihi6wVG
gqXGHLvAhWhbUrE3gv.WLFJ9EzqhsHDvEDD.wAtAc3ZgvT8dhAWQtAXb.vCu
z0EC7qWnNHgDG.P3.rSk7CWBW5rLvwA6Ab5v1UaVSSSUrMrMDppYYntb1gtd
LGdQ4NpU24gqwW.vw0QwK.Nveo+QXgH3o5JkxWqbez6wdwsHENtZpdrE3kCx
mRd1l7nDpXehdPSMtVqRr48ZoJtol8t+yMsJuOn4fpBT3TGkz4qLNfXwEFIG
FnYmjBbSgV0T5gxBKqn9RUcKqv1cR+cem+US+ZzDZEWXaEmoJhPMBsJ21HBZ
lN8a1YmkS2PY8JTyQd2PYYT0R3eyDFjnLspfhHt2PhYQx0YIdnNHCCUUJHuN
nGfSjON1w810wqitEBIjaWI+yn3DhS...gHjc2hZzXE0aFhKyyEaOB0kg1v3
rETxolQ+naH+kvfQfgigDFfQ2JHqCVLI0gd70MhpdQc1EvzauGTMHZ0IV1WO
l0MpWo5Mmrdz2w4HpopA2qGgH.xA3fPKDWEQtP5MDgqa0Err+i69GYwkROWE
28KQOaEbWC5VzePYpsH2Z7HRM5IYGp0EqDF9h8f.gHrdMdIve0JOfWBv0wEP
B7Cz0Cy0t26b81ZsVHsTjDVkLrAtiQigBUVnHbRdXUQVZbzqr7jgoNye6DeD
Q3QYJXyV2+z2AYixFnLX06PZFayfEQtQu1kkHqvYySwGHKvib9KyklCC3NJ9
4M+rNfqt0vsbc0o1s6T218qY6wqW6t0psRwOTMZKuu87uO+OAdAc52B
-----------end_max5_patcher-----------
</code></pre>

**Comment by fde31** [comment]
OK seems like the code basically just handles the top level key and isn't aware of this being a nested object structure.
