### ISSUE TITLE
clicking the instances view then reloading the webpage gives a 404

### ISSUE THREAD

**Issue by x37v** [Cycling74/rnbo-runner-panel#131]
1. load a patcher instance
2. click the gear on that instance
3. hit command-r or ctrl-r depending on your OS

see 404

`v2.0.2-beta.2`

**Comment by fde31** [comment]
hmmm can't reproduce. is the interface running on the runner or on your machine? Are you not being redirected to the correct route incl. query params? What's the URL?

**Comment by fde31** [comment]
OK, clarified this happens when running on the pi itself as the filename for the instance route is dynamic with `/instances/[index].html`.

Guess one way would be to add redirects on the python server to ensure that `/instances/\d+(.*)$` gets redirected somewhere, maybe just `/`

**Comment by x37v** [comment]
looks like there was already some work around a similar thing in #23 .. so maybe we just need to expand on that
