### ISSUE TITLE
buffer mapping popup goes away before i can click it

### ISSUE THREAD

**Issue by x37v** [Cycling74/rnbo-runner-panel#134]
https://github.com/Cycling74/rnbo-runner-panel/assets/65796/4af15552-ad5f-4b54-9ae3-726a1c5d584f

**Comment by fde31** [comment]
that's bc the sorted list of datafiles is a derived, non-memoized selector currently. This wasn't an issue before given that we didn't have consistent dynamic state updates that would cause the reference checks to return false. However, with the CPU load updating frequently we need to memoize derived data
