### ISSUE TITLE
rpi web interface: New Patcher instance is not in view

### ISSUE THREAD

**Issue by nyboer** [Cycling74/rnbo-runner-panel#168]
When I add a new patcher instance, it is not visible in the browser window. It appears several pixels below. This movie demonstrates what I see, and adds a couple suggestions of where a new instance could land.
https://github.com/user-attachments/assets/c4243e54-99c0-42aa-919e-17c903ca477a

**Comment by fde31** [comment]
As discussed - one aspect of  improving this is to track the current viewport in the application state and ensure that we place the node within that.
