### ISSUE TITLE
FR: Set Global MIDI Mapping View

### ISSUE THREAD

**Issue by twhiston** [Cycling74/rnbo-runner-panel#171]
It would be really useful if there was a view in the interface which showed you only the controls which you have mapped to midi input, across all of your instantiated patchers. This would be very useful not only for a performance overview display but for when you are setting up mapping midi controllers across a number of patchers. Currently it's a bit of a chore to see if a midi input is assigned to something as you have to go through all of your current patcher instances and look for it. As midi mapping and complex patchers do tend to evolve over time having an easy way to get a quick overview of all your mappings would be very helpful.

**Comment by fde31** [comment]
Hi @twhiston. Yeah that sounds reasonable, I assume some sort of non-patcher bound list / table that shows all the actively mapped parameters with the MIDI info alongside which patcher instance the parameter is in? Is there any other information that you would need to see in there in order to have it address your use-case?

**Comment by twhiston** [comment]
Would be fantastic if it could show the current value of the parameter too, could just be the sliders like we already have in the patchers, or just the current value if the sliders take up too much space, so you have some kind of performance overview of your current state along with the mapping info. I also wouldn't be against it being 2 views, so one with all the extended parameter info, what is mapped to what, which parameter instance it is in etc... and another which has all the mapped controls and their sliders/values.
Thanks very much for considering implementing this!

**Comment by fde31** [comment]
OK I'd like to split this into two FRs:

* a global "MIDI Map" view to see mappings across all instances in the graph with their mapping info and value
* for the sake of a better word a sort of "Performance View" functionality that allows u to add / remove and sort parameters from all devices

The latter is probably gonna follow the existing slider view functionality but with the ability to alter which parameters are shown.

For the former I'd currently think of something that, even if simplified in functionality, resembles the MIDI Mapping table in Max in a way. Does that make sense?

**Comment by twhiston** [comment]
That sounds great to me!

Do you see allowing editing of the midi mappings from the mapping page?

**Comment by fde31** [comment]
Take it with a grain of salt given there is no work / code on this yet, but I don't see why we couldn't add this
