### ISSUE TITLE
some graph connections are made but not shown

### ISSUE THREAD

**Issue by x37v** [Cycling74/rnbo-runner-panel#174]
related to #173 

If I run the runner with pipewire, I can make connections to the `Midi-Bridge` node but the gui doesn't show them.

you can test this by doing the following:

```
sudo apt-get install pipewire-jack
sudo reboot
....
sudo service rnbooscquery stop
pw-jack /usr/bin/rnbooscquery
```

this will run the runner against pipewire as installing it will make it run by default (or at least does on my machine)

**Comment by sadguitarius** [comment]
Could this possibly have something to do with port names containing spaces?

**Comment by sadguitarius** [comment]
Hey @x37v, I've made some progress with this! Can you check out my branch [here](https://github.com/sadguitarius/rnbo-runner-panel/tree/pipewire-connection-fix) and let me know if this works for you? It's entirely possible that this also depends on some pipewire settings being set a certain way, so let me know. I haven't done any exhaustive testing yet, but I'm at least able to make and delete connections, and the connections seem to be showing up the same when checking with `jack_lsp -c`. I'm also treating pipewire "Midi-Bridge" ports as system ports so the I/O is split in the interface, which does help somewhat with the overlapping text, but it's not perfect yet. I'm sure you'd know how to clean that up a bit more. Anyway, let me know what you think. Thanks!

**Comment by sadguitarius** [comment]
And the latest push gets rid of capture/playback in the port labels, since that's not needed when the ports visually indicate what type of port they are anyway. Hopefully this keeps the names short enough not to go over the box boundary.
