### ISSUE TITLE
FR: dataref mapping and management

### ISSUE THREAD

**Issue by x37v** [Cycling74/rnbo-runner-panel#60]
* allow for a user to map a dataref `[buffer~ foo]` to a soundfile and also show what is mapped (rnbo.remote does it, `data_ref/foo`)
* stretch goals (requires runner updates):
  * list files available
  * allow users to delete files
  * allow users to upload files

**Comment by x37v** [comment]
dependent on this ticket:  19214

**Comment by fde31** [comment]
see #106 ?

**Comment by x37v** [comment]
we now have mapping but not upload or delete
