### ISSUE TITLE
FR: set 'initial preset' for a patcher

### ISSUE THREAD

**Issue by x37v** [Cycling74/rnbo-runner-panel#94]
the runner has the ability to set the initial preset that should load after you load a patcher, would be nice to have this available in the web interface

https://cycling74.com/forums/autoload-a-preset-on-start-on-raspberry-and-rnbo

**Comment by fde31** [comment]
what's the path in the OSCQuery state tree for that? I see something like `http://c74rpi4.local:5678/rnbo/inst/0/presets/initial` which leads to a few questions:

* the path hints that presets are instance, not patcher specific. So when creating a new instance of the same patcher, what is supposed to happen?
* there is no path to show the preset that will be loaded per default or am I missing something?

**Comment by x37v** [comment]
@fde31 yeah.. currently the initial preset is associated with the patcher so it would load if you created another instance but I suspect that I'd have to update the runner to broadcast changes just like i did for when you save or delete a preset from an instance.
I'm not sure what you mean by "be loaded per default" .. isn't that `presets/initial` ?

**Comment by x37v** [comment]
maybe we should just change the interface and make it a preset called `initial`
